// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwShEiX_HbB4vqLUvonLO1fCXOgRdnbYw',
    appId: '1:580710277390:web:2829c0731e758f4089775f',
    messagingSenderId: '580710277390',
    projectId: 'rewardapp-87211',
    authDomain: 'rewardapp-87211.firebaseapp.com',
    storageBucket: 'rewardapp-87211.appspot.com',
    measurementId: 'G-D1VPZXM8K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDymfmZTm7n2yP7M6AZ0GFLLfXliYFNeHo',
    appId: '1:580710277390:android:a3e0b4e1ba6c4d0e89775f',
    messagingSenderId: '580710277390',
    projectId: 'rewardapp-87211',
    storageBucket: 'rewardapp-87211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrvBxwfHQK0ZFjV6revjUQ8Pksh-fzfvk',
    appId: '1:580710277390:ios:679821e86ebbdb8589775f',
    messagingSenderId: '580710277390',
    projectId: 'rewardapp-87211',
    storageBucket: 'rewardapp-87211.appspot.com',
    iosBundleId: 'com.example.ge2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrvBxwfHQK0ZFjV6revjUQ8Pksh-fzfvk',
    appId: '1:580710277390:ios:679821e86ebbdb8589775f',
    messagingSenderId: '580710277390',
    projectId: 'rewardapp-87211',
    storageBucket: 'rewardapp-87211.appspot.com',
    iosBundleId: 'com.example.ge2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwShEiX_HbB4vqLUvonLO1fCXOgRdnbYw',
    appId: '1:580710277390:web:22fc7eca0b72b46889775f',
    messagingSenderId: '580710277390',
    projectId: 'rewardapp-87211',
    authDomain: 'rewardapp-87211.firebaseapp.com',
    storageBucket: 'rewardapp-87211.appspot.com',
    measurementId: 'G-PWFELKST0X',
  );
}
